url: "http://eracom-id471.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/projet-3--LouisTacheron" # the subpath of your site, e.g. /blog
title: "L'actu de Louis" # the name of your site, e.g. ACME Corp.
